// Class automatically generated by Dev-C++ New Class wizard


#ifndef DECK_H
#define DECK_H

#include "card.h"
#include <iostream>
#include <windows.h>
/*
 * No description
 */
class Deck
{
public:
		Deck();
		~Deck();

        // Get and set methods for the instance variable top
        int getTop();
        void setTop(int);
		

        Card* getCard(int);
        
        void initializeDeck();     // Assigns values to the cards in the deck
		void initializeColour();	//XX
        void displayDeck(bool);    // Displays the contents of the deck
                                   // bool : position beside the card
		void displayDeckWithColour(bool);	//bool : position beside the card XX
        void shuffleDeck();        // Shuffles the deck

        void dealCard(Deck *);         // Accepts a pointer which represents the deck where the card 
                                       // will be dealt to.

        void moveCard(Deck *, int);   // Accepts a pointer to a deck and an integer
                                         // The pointer represents the destination of the card
                                         // being discarded and the integer represents the
                                         // position of the cards being discarded


        void rebalanceHand(int n);    // After the card in position n is removed from the hand it needs 
                                      // to be removed from the array and all other cards shifted down.
                                      // This will keep the deck sorted.

        void sortHand();              // Sorts the deck by suit and rank.

private:
		Card pile[52];      // An array which contains all the cards
		int top;            // top represents the location in the array of the top card
							// The top will be the LARGEST position in the array which
							// contains a card.
  
};

#endif // DECK_H
